# During build and run, set environment DOMAIN pointing
# to publicly accessible domain where app will be hosted
services:
  app:
    image: reckon
    build:
      context: .
      args:
        API_URL: https://${DOMAIN:-http://localhost:8000}
    environment:
      API_URL: "https://${DOMAIN:-http://localhost:8000}"
      DB_URL: "postgresql://reckon:+bX2NBT~;oa?@reckon-db.postgres.database.azure.com:5432/reckon"
      TRANSFORMERS_CACHE: "/tmp/.cache/huggingface/hub"
    ports:
      - 8000:8000
      - 3000:3000   
  webserver:
    environment:
      DOMAIN: ${DOMAIN:-localhost}
      API_URL: "app:8000"
      UI_URL: "app:3000"
    ports:
      - 443:443
      - 80:80  # for acme-challenge via HTTP
    build:
      context: .
      dockerfile: Caddy.Dockerfile
    depends_on:
      - app