"""empty message

Revision ID: 1e74c26f659f
Revises: 729e2f95ed06
Create Date: 2024-02-21 22:14:09.892494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1e74c26f659f'
down_revision: Union[str, None] = '729e2f95ed06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reckoning', sa.Column('parent_total_comments', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reckoning', 'parent_total_comments')
    # ### end Alembic commands ###
