"""empty message

Revision ID: 729e2f95ed06
Revises: c6b51f6e722c
Create Date: 2024-02-21 19:58:43.760457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '729e2f95ed06'
down_revision: Union[str, None] = 'c6b51f6e722c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    op.add_column('reckoning', sa.Column('parent_type', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('reckoning', sa.Column('parent_id', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('reckoning', sa.Column('parent_user_vote_history', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('reckoning', sa.Column('parent_up_votes', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('reckoning', sa.Column('parent_down_votes', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reckoning', 'parent_down_votes')
    op.drop_column('reckoning', 'parent_up_votes')
    op.drop_column('reckoning', 'parent_user_vote_history')
    op.drop_column('reckoning', 'parent_id')
    op.drop_column('reckoning', 'parent_type')
    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reckoning_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reckoning_id'], ['reckoning.id'], name='embeddings_reckoning_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='embeddings_pkey')
    )
    # ### end Alembic commands ###
