"""empty message

Revision ID: 9175d240c0f3
Revises: 983b79e11bf8
Create Date: 2024-03-08 19:34:33.896565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9175d240c0f3'
down_revision: Union[str, None] = '983b79e11bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reckoning', sa.Column('parent_supports', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('reckoning', sa.Column('parent_detracts', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('reckoning', sa.Column('parent_points_of_order', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('reckoning', sa.Column('parent_elapsed_time', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reckoning', 'parent_elapsed_time')
    op.drop_column('reckoning', 'parent_points_of_order')
    op.drop_column('reckoning', 'parent_detracts')
    op.drop_column('reckoning', 'parent_supports')
    # ### end Alembic commands ###
