"""empty message

Revision ID: 983b79e11bf8
Revises: 9d68dc20042c
Create Date: 2024-03-08 17:25:45.951700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '983b79e11bf8'
down_revision: Union[str, None] = '9d68dc20042c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reckoning', sa.Column('elapsed_time', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reckoning', 'elapsed_time')
    # ### end Alembic commands ###
