"""empty message

Revision ID: 9d68dc20042c
Revises: 1e74c26f659f
Create Date: 2024-03-06 11:02:05.892671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9d68dc20042c'
down_revision: Union[str, None] = '1e74c26f659f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reckoning', sa.Column('depth', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reckoning', 'depth')
    # ### end Alembic commands ###
