"""empty message

Revision ID: d947530f7ee9
Revises: a1e0f41ee875
Create Date: 2024-02-18 23:13:46.116045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd947530f7ee9'
down_revision: Union[str, None] = 'a1e0f41ee875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    op.add_column('feedback', sa.Column('subject_reckoning_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'reckoning', ['subject_reckoning_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'subject_reckoning_id')
    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reckoning_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reckoning_id'], ['reckoning.id'], name='embeddings_reckoning_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='embeddings_pkey')
    )
    # ### end Alembic commands ###
