"""empty message

Revision ID: e1486a5edd23
Revises: d947530f7ee9
Create Date: 2024-02-19 22:25:29.422076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e1486a5edd23'
down_revision: Union[str, None] = 'd947530f7ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reckoning', sa.Column('total_comments', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.drop_column('reckoning', 'supports_detracts_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reckoning', sa.Column('supports_detracts_ratio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reckoning', 'total_comments')
    # ### end Alembic commands ###
