"""empty message

Revision ID: e1a694ee11b8
Revises: 9175d240c0f3
Create Date: 2025-10-22 12:12:26.803086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e1a694ee11b8'
down_revision: Union[str, None] = '9175d240c0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_embeddings_embedding'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')

    op.drop_table('embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('reckoning_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reckoning_id'], ['reckoning.id'], name=op.f('embeddings_reckoning_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reckoning_id', name=op.f('embeddings_pkey'))
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_embeddings_embedding'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')

    # ### end Alembic commands ###
