"""empty message

Revision ID: f7d5625b6052
Revises: bbf33e6bbc33
Create Date: 2024-02-21 00:20:19.772887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f7d5625b6052'
down_revision: Union[str, None] = 'bbf33e6bbc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    op.add_column('reckoning', sa.Column('parent_content', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reckoning', 'parent_content')
    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reckoning_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reckoning_id'], ['reckoning.id'], name='embeddings_reckoning_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='embeddings_pkey')
    )
    # ### end Alembic commands ###
