GRANT CONNECT ON DATABASE reckon TO posthog;
GRANT USAGE ON SCHEMA public TO posthog;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO posthog;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO posthog;
