"""Bootstrap and run Alembic migrations.

Handles:
- alembic_version table doesn't exist → stamps based on detected tables
- alembic_version has an unknown revision → overwrites with correct stamp
- alembic_version has a known revision → runs alembic upgrade head as normal

Usage:
    python scripts/db_migrate.py
"""

import os
import subprocess
import sys

from sqlalchemy import create_engine, text, inspect

# Known migration revisions in our chain (oldest first)
KNOWN_REVISIONS = {
    "5c4374b3a58f",
    "b2f1a9c4d7e3",
    "c3d4e5f6a7b8",
    "d4e5f6a7b8c9",
    "1a879f6b06c3",
}


def get_db_url() -> str:
    """Get database URL from environment, falling back to alembic.ini."""
    url = os.getenv("DB_URL")
    if url:
        return url
    import configparser

    cfg = configparser.ConfigParser()
    cfg.read("alembic.ini")
    return cfg.get("alembic", "sqlalchemy.url")


def detect_stamp_revision(inspector, tables: list[str]) -> str | None:
    """Detect the correct Alembic revision to stamp based on existing tables."""
    has_debate_table = "debate" in tables
    has_user_table = "user" in tables

    if not has_debate_table:
        return None  # No old migrations applied, stamp at head

    # debate table exists → c3d4e5f6a7b8 was applied
    # Check if d4e5f6a7b8c9 (user verification) was also applied
    has_verification = False
    if has_user_table:
        cols = [c["name"].lower() for c in inspector.get_columns("user")]
        has_verification = "verification_token" in cols

    return "d4e5f6a7b8c9" if has_verification else "c3d4e5f6a7b8"


def main():
    db_url = get_db_url()
    print(f"[migrate] Connecting to database...", flush=True)

    engine = create_engine(db_url)
    inspector = inspect(engine)

    tables = inspector.get_table_names()
    print(f"[migrate] Existing tables: {', '.join(sorted(tables))}", flush=True)

    has_version_table = "alembic_version" in tables
    current_revision = None

    if has_version_table:
        with engine.connect() as conn:
            result = conn.execute(text("SELECT version_num FROM alembic_version"))
            row = result.fetchone()
            current_revision = row[0] if row else None
            print(f"[migrate] alembic_version exists, revision: {current_revision}", flush=True)

    # If the revision is unknown (auto-generated by reflex db init), fix it
    if has_version_table and current_revision and current_revision not in KNOWN_REVISIONS:
        print(f"[migrate] Unknown revision {current_revision} — likely auto-generated.", flush=True)
        stamp_rev = detect_stamp_revision(inspector, tables)
        if stamp_rev:
            print(f"[migrate] Overwriting with correct revision: {stamp_rev}", flush=True)
            with engine.connect() as conn:
                conn.execute(text("DELETE FROM alembic_version"))
                conn.execute(text(f"INSERT INTO alembic_version (version_num) VALUES ('{stamp_rev}')"))
                conn.commit()
            current_revision = stamp_rev
        else:
            # No tables at all — let alembic handle it from scratch
            print(f"[migrate] No existing tables, clearing alembic_version for fresh migration.", flush=True)
            with engine.connect() as conn:
                conn.execute(text("DELETE FROM alembic_version"))
                conn.commit()
            current_revision = None
    elif not has_version_table:
        stamp_rev = detect_stamp_revision(inspector, tables)
        if stamp_rev:
            print(f"[migrate] alembic_version missing. Stamping at {stamp_rev}...", flush=True)
            with engine.connect() as conn:
                conn.execute(
                    text(
                        "CREATE TABLE IF NOT EXISTS alembic_version "
                        "(version_num VARCHAR(32) NOT NULL, PRIMARY KEY (version_num))"
                    )
                )
                conn.execute(
                    text(f"INSERT INTO alembic_version (version_num) VALUES ('{stamp_rev}')")
                )
                conn.commit()
            print(f"[migrate] Stamped at {stamp_rev}.", flush=True)
        else:
            print(
                f"[migrate] No existing tables. Running full migration from scratch...",
                flush=True,
            )

    engine.dispose()

    # Run alembic upgrade head via CLI
    print(f"[migrate] Running: alembic upgrade head...", flush=True)
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    env = os.environ.copy()
    env["DB_URL"] = db_url
    result = subprocess.run(
        ["alembic", "upgrade", "head"],
        cwd=repo_root,
        env=env,
        capture_output=True,
        text=True,
    )
    if result.stdout:
        print(result.stdout.strip(), flush=True)
    if result.stderr:
        print(result.stderr.strip(), flush=True)
    if result.returncode != 0:
        print(f"[migrate] ERROR: alembic upgrade head failed (exit {result.returncode})", flush=True)
        sys.exit(result.returncode)

    print(f"[migrate] Migration complete.", flush=True)


if __name__ == "__main__":
    main()